#!/usr/bin/env bash

if [[ ${UID} == 0 ]]
then echo "[provision] Must not be run as root." >&2 ; exit 1
fi

# Variables passed in from terraform, see aws-vpc.tf, the "remote-exec" provisioner
awsKeyID=${1}
awsAccessKey=${2}
awsRegion=${3}
awsVPC=${4}
boshSubnet=${5}
ipMask=${6}
bastionAZ=${7}
bastionID=${8}
boshType=${9}
boshInitVersion="${10}"
boshDirectorIP="52.6.205.61" # TODO: Pass the Director's Elastic IP in...

echoh "[provision] Provisioning! Detailed output may be found later at $HOME/provision.log"

echo "[provision] Configuring PATH..."
{
  mkdir $HOME/bin 
  echo 'PATH="$PATH:$HOME/bin"' >> "$HOME/.bashrc"
} &>>$HOME/provision.log

echo "[provision] Configuring SSH Keys..."
{
  ssh-keygen -t rsa -b 4096 -N '' -C 'bosh-aws-vpc-jumpbox' -f $HOME/.ssh/id_rsa
  touch $HOME/.ssh/known_hosts
  chmod 0640 $HOME/.ssh/known_hosts
  for file in $HOME/sshkeys/* 
  do cat ${file} >> ${HOME}/.ssh/known_hosts 
  done
  chmod 0600 $HOME/.ssh/bosh.pem
} &>>$HOME/provision.log

echo "[provision] Installing Packages... (output may be found later at $HOME/yum.install.log)"
{
  sudo yum install -y tmux screen gpg vim gcc mysql-devel postgresql-devel postgresql-libs sqlite-devel libxslt-devel libxml2-devel yajl-ruby patch
} &>>$HOME/provision.log

echo "[provision] Installing RVM & Ruby... (output may be found later at $HOME/rvm.install.log)"
{
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  curl -sO https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
  curl -sO https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
  gpg --verify rvm-installer.asc && bash rvm-installer stable &>>$HOME/rvm.install.log
  rm -f rvm-installer*
  source "$HOME/.rvm/scripts/rvm" # So changes take effect in the current env
  rvm install ruby
  rvm use ruby --default
} &>>$HOME/provision.log

echo "[provision] Installing BOSH CLI..."
{
  gem install bosh_cli --no-rdoc --no-ri
  bosh -v
} &>>$HOME/provision.log

echo "[provision] Installing bosh-init..."
{
  boshInitURL="https://s3.amazonaws.com/bosh-init-artifacts/bosh-init-${boshInitVersion}-linux-amd64" 
  curl -sL ${boshInitURL} -o $HOME/bin/bosh-init
  chmod +x ~/bin/bosh-init
  bosh-init -v
} &>>$HOME/provision.log

echo "[provision] Deploying the BOSH Director using bosh-init"
{
  $HOME/bin/bosh-init deploy $HOME/config/aws/staging/bosh.yml
} 2>&1 | tee -a $HOME/provision.log

#echo "[provision] Targeting Director..."
#bosh target ${boshDirectorIP}

